name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build CLI tool
      run: cargo build --example cli --release --verbose
    - name: Upload CLI tool
      uses: actions/upload-artifact@v1
      with:
        name: simpleonvif-cli
        path: target/release/examples/cli
